<?php

use Illuminate\Database\Seeder;

class SectionsTableSeeder extends Seeder {

	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run() {

		DB::statement('SET FOREIGN_KEY_CHECKS=0');
		DB::statement('TRUNCATE TABLE sections');

		DB::table('sections')->insert([
			[
				'project_id'    => 1,
				'name'          => '路基第一合同段',
				'type_id'       => 1,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路基第二合同段',
				'type_id'       => 1,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路基第三合同段',
				'type_id'       => 1,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路基第四合同段',
				'type_id'       => 1,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路基第五合同段',
				'type_id'       => 1,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路基第六合同段',
				'type_id'       => 1,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路基隧道标合同段',
				'type_id'       => 1,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路面第一合同段',
				'type_id'       => 2,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路面第二合同段',
				'type_id'       => 2,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			], [
				'project_id'    => 1,
				'name'          => '路面第三合同段',
				'type_id'       => 2,
				'building'      => '建设方',
				'constructor'   => '施工方',
				'investment'    => '12254562.12',
				'kilometre'     => '548874.21',
				'address'       => '工程地址',
				'begtime'       => '2003-10-04',
				'endtime'       => '2020-05-02',
				'authority'     => '主管税务机关',
				'bureau'        => '主管税务分局',
				'finance'       => '财务负责人',
				'finance_phone' => '12345678903',
				'bank'          => '开户银行',
				'bank_name'     => '开户行名称',
				'bank_account'  => '25478632145',
			],
		]);

		DB::statement('SET FOREIGN_KEY_CHECKS=1');
	}
}
